openapi: 3.0.3

info:
  title: Conference Room Booking API
  description: >
    An API for managing conference rooms and room bookings within an organisation.
    The API allows clients to retrieve rooms, create and cancel bookings, and check
    room availability. This specification is documentation-only and is designed to be
    understood without any backend implementation.
  version: 1.0.0
  contact:
    name: API Support
    email: support@conferenceroombooking.com

servers:
  - url: https://api.staging.conferenceroombooking.com
    description: Staging server
  - url: https://api.conferenceroombooking.com
    description: Production server

security:
  - bearerAuth: []

paths:

  /rooms:
    get:
      summary: Retrieve all conference rooms
      description: Returns a list of all available conference rooms.
      responses:
        '200':
          description: List of rooms
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Room'

    post:
      summary: Create a new conference room
      description: Creates a new conference room.
      responses:
        '201':
          description: Room created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Room'

  /rooms/{roomId}:
    get:
      summary: Retrieve a single conference room
      parameters:
        - name: roomId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Room details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Room'
        '404':
          description: Room not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    put:
      summary: Update a conference room
      parameters:
        - name: roomId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Room updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Room'

    delete:
      summary: Delete a conference room
      parameters:
        - name: roomId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Room deleted

  /bookings:
    get:
      summary: Retrieve all bookings
      description: Returns a list of all room bookings.
      responses:
        '200':
          description: List of bookings
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Booking'

    post:
      summary: Create a booking
      description: Creates a booking for a conference room.
      responses:
        '201':
          description: Booking created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Booking'
        '409':
          description: Booking conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /bookings/{bookingId}:
    delete:
      summary: Cancel a room booking
      description: Cancels an existing booking for a conference room.
      parameters:
        - name: bookingId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Booking successfully cancelled
        '404':
          description: Booking not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /rooms/availability:
    get:
      summary: Check room availability
      description: Checks whether a conference room is available for a given date and time.
      parameters:
        - name: date
          in: query
          required: true
          schema:
            type: string
            format: date
        - name: startTime
          in: query
          required: true
          schema:
            type: string
        - name: endTime
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Availability result
          content:
            application/json:
              schema:
                type: object
                properties:
                  roomId:
                    type: string
                  available:
                    type: boolean

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Room:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        capacity:
          type: integer
        equipment:
          type: array
          items:
            type: string

    Booking:
      type: object
      properties:
        bookingId:
          type: string
        roomId:
          type: string
        date:
          type: string
          format: date
        startTime:
          type: string
        endTime:
          type: string
        bookedBy:
          type: string

    Error:
      type: object
      properties:
        error:
          type: string
